ignoredBuiltDependencies:
  - sharp ## Install script is only required when compiling sharp from source - https://sharp.pixelplumbing.com/install

nodeLinker: isolated

overrides:
  "@typescript-eslint/eslint-plugin": "^8"
  "@typescript-eslint/parser": "^8"
