---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: website-update-flickr
  namespace: website
spec:
  schedule: "21 2 * * *" ## 2:21 UTC
  successfulJobsHistoryLimit: 16
  failedJobsHistoryLimit: 32
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: main
              image: curlimages/curl:7.88.1
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                runAsUser: 999
              command:
                - /bin/sh
                - -ec
                - curl --no-progress-meter --fail https://kachkaev.uk/update-profiles/${PROFILE_NAME}?${SECURITY_TOKEN}; [ $? -eq 0 ]  || exit 1
              env:
                - name: PROFILE_NAME
                  value: flickr
                - name: SECURITY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-profile
                      key: security-token
              resources:
                requests:
                  memory: 16Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
                  cpu: 200m
          restartPolicy: Never

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: website-update-github
  namespace: website
spec:
  schedule: "22 2 * * *"
  successfulJobsHistoryLimit: 16
  failedJobsHistoryLimit: 32
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: main
              image: curlimages/curl:7.88.1
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                runAsUser: 999
              command:
                - /bin/sh
                - -ec
                - curl --no-progress-meter --fail https://kachkaev.uk/update-profiles/${PROFILE_NAME}?${SECURITY_TOKEN}; [ $? -eq 0 ]  || exit 1
              env:
                - name: PROFILE_NAME
                  value: github
                - name: SECURITY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-profile
                      key: security-token
              resources:
                requests:
                  memory: 16Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
                  cpu: 200m
          restartPolicy: Never

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: website-update-openaccess
  namespace: website
spec:
  schedule: "23 2 * * 0" ## 2:23 UTC on Sundays
  successfulJobsHistoryLimit: 16
  failedJobsHistoryLimit: 32
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: main
              image: curlimages/curl:7.88.1
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                runAsUser: 999
              command:
                - /bin/sh
                - -ec
                - curl --no-progress-meter --fail https://kachkaev.uk/update-profiles/${PROFILE_NAME}?${SECURITY_TOKEN}; [ $? -eq 0 ]  || exit 1
              env:
                - name: PROFILE_NAME
                  value: openaccess
                - name: SECURITY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-profile
                      key: security-token
              resources:
                requests:
                  memory: 16Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
                  cpu: 200m
          restartPolicy: Never

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: website-update-linkedin
  namespace: website
spec:
  schedule: "24 2 * * *"
  successfulJobsHistoryLimit: 16
  failedJobsHistoryLimit: 32
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: main
              image: curlimages/curl:7.88.1
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                runAsUser: 999
              command:
                - /bin/sh
                - -ec
                - curl --no-progress-meter --fail https://kachkaev.uk/update-profiles/${PROFILE_NAME}?${SECURITY_TOKEN}; [ $? -eq 0 ]  || exit 1
              env:
                - name: PROFILE_NAME
                  value: linkedin
                - name: SECURITY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-profile
                      key: security-token
              resources:
                requests:
                  memory: 16Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
                  cpu: 200m
          restartPolicy: Never

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: website-update-osm
  namespace: website
spec:
  schedule: "25 2 * * *"
  successfulJobsHistoryLimit: 16
  failedJobsHistoryLimit: 32
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: main
              image: curlimages/curl:7.88.1
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                runAsUser: 999
              command:
                - /bin/sh
                - -ec
                - curl --no-progress-meter --fail https://kachkaev.uk/update-profiles/${PROFILE_NAME}?${SECURITY_TOKEN}; [ $? -eq 0 ]  || exit 1
              env:
                - name: PROFILE_NAME
                  value: osm
                - name: SECURITY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-profile
                      key: security-token
              resources:
                requests:
                  memory: 16Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
                  cpu: 200m
          restartPolicy: Never

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: website-update-twitter-en
  namespace: website
spec:
  schedule: "26 2,10,18 * * *" ## 2:26, 10:26, 18:26 UTC
  successfulJobsHistoryLimit: 16
  failedJobsHistoryLimit: 32
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: main
              image: curlimages/curl:7.88.1
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                runAsUser: 999
              command:
                - /bin/sh
                - -ec
                - curl --no-progress-meter --fail https://kachkaev.uk/update-profiles/${PROFILE_NAME}?${SECURITY_TOKEN}; [ $? -eq 0 ]  || exit 1
              env:
                - name: PROFILE_NAME
                  value: twitter-en
                - name: SECURITY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-profile
                      key: security-token
              resources:
                requests:
                  memory: 16Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
                  cpu: 200m
          restartPolicy: Never

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: website-update-twitter-ru
  namespace: website
spec:
  schedule: "27 2,10,18 * * *" ## 2:27, 10:27, 18:27 UTC
  successfulJobsHistoryLimit: 16
  failedJobsHistoryLimit: 32
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: main
              image: curlimages/curl:7.88.1
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                runAsUser: 999
              command:
                - /bin/sh
                - -ec
                - curl --no-progress-meter --fail https://kachkaev.uk/update-profiles/${PROFILE_NAME}?${SECURITY_TOKEN}; [ $? -eq 0 ]  || exit 1
              env:
                - name: PROFILE_NAME
                  value: twitter-ru
                - name: SECURITY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-profile
                      key: security-token
              resources:
                requests:
                  memory: 16Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
                  cpu: 200m
          restartPolicy: Never
